Sort imports
Becklyn/prettier pull request #1
Opened 2023-07-26 10:05 UTC by felixhasse

Update the prettier config to sort imports. For that to work, https://github.com/trivago/prettier-plugin-sort-imports needs to be installed as a devDependency in the parent project.

Imports are sorted in the following order:
1.  React imports
2. Next.js
3. Mayd
4. Imports from installed packages
5. Relative imports

Within these categories, imports are sorted alphabetically

2023-07-26 10:17 UTC, mangoischke requested changes

2023-07-26 10:17 UTC, mangoischke commented on .prettierrc.json
> +}
```suggestion
}

```

2023-07-26 10:17 UTC, mangoischke commented on README.md
>  npm install --save-dev prettier
```suggestion
npm install --save-dev prettier @trivago/prettier-plugin-sort-imports
```

2023-07-26 10:17 UTC, mangoischke commented on README.md
> +```
👋

2023-07-27 11:34 UTC, timfuhrmann requested changes

2023-07-27 11:34 UTC, timfuhrmann commented on .prettierrc.json
> +    "importOrderSeparation": true,
As discussed:
```suggestion
    "importOrderSeparation": false,
```

2023-07-27 11:34 UTC, timfuhrmann commented on .prettierrc.json
> +        "^@mayd/(.*)$",
And I guess we should escape `/`, shouldn't we?

```suggestion
        "^next(.*)$",
        "^@fr(e|a)ym\/(.*)$",
        "^@mayd\/(.*)$",
```

2023-07-27 13:48 UTC, timfuhrmann approved these changes

2023-07-27 13:49 UTC, merged